### ISSUE TITLE
Alias Handling in Contao 4.x

### ISSUE THREAD

**Issue by akroii** [pdir/mae_event_categories#12]
Wenn man `Frühling` als Alias vergibt wird `fr%25C3%25BChling` daraus im frontend.
Sofern ich mich richtig erinnere kann Contao utf8 chars in der URL darstellen.

Können Sie das bitte fixen?
Backend:
![bildschirmfoto 2018-01-23 um 10 27 36](https://user-images.githubusercontent.com/8830861/35267950-268ba8ca-0028-11e8-935c-313e1ef38275.png)

Frontend:
![bildschirmfoto 2018-01-23 um 10 26 22](https://user-images.githubusercontent.com/8830861/35267960-2b2b4106-0028-11e8-8e3b-ec6460fad39e.png)

Frontend-URL:
![bildschirmfoto 2018-01-23 um 10 26 25](https://user-images.githubusercontent.com/8830861/35267955-292397a0-0028-11e8-8898-308541993517.png)

**Comment by MDevster** [comment]
fixed in version 1.5.2
