### ISSUE TITLE
Kategorien werden nicht angezeigt, wenn das Weiterleitungsziel auf individuelle URL gesetzt wird

### ISSUE THREAD

**Issue by chriza** [pdir/mae_event_categories#20]
Hallo,

ich habe eine Contao 4.13.14 Installation mit php 7.4.xx

Im Backend Eventeinstellungen wird die Kategorieauswahl nicht angezeigt, wenn das Weiterleitungziel des Events auf individuelle URL gesetzt wird.

![grafik](https://user-images.githubusercontent.com/1572887/205009427-020fce7b-ab6d-4b31-85c5-dd15da1c25c9.png)

![grafik](https://user-images.githubusercontent.com/1572887/205009511-39e02778-ca9d-4bf5-9818-6e9889049734.png)

**Comment by lizardat** [comment]
Ich habe das gleiche Problem. Kategorien werden im Backend nur bei "Standard" zur Auswahl gestellt.

**Comment by lizardat** [comment]
wer das selbst lösen will:
unter contao > dca > tl_calender_events.php

`<?php

// adds category selection in backend

use Contao\CoreBundle\DataContainer\PaletteManipulator;

PaletteManipulator::create()
->addField('categories', 'title_legend', 'append')
->applyToPalette('default', 'tl_calendar_events')
->applyToPalette('internal', 'tl_calendar_events')
->applyToPalette('article', 'tl_calendar_events')
->applyToPalette('external', 'tl_calendar_events');

$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['categories'] = array
(
    'label'                   => &$GLOBALS['TL_LANG']['tl_calendar_events']['categories'],
    'exclude'                 => true,
    'filter'                  => true,
    'inputType'               => 'checkboxWizard',
    'foreignKey'              => 'tl_mae_event_cat.title',
    'eval'                    => array('tl_class'=>'clr', 'multiple'=>true, 'fieldType'=>'checkbox', 'foreignTable'=>'tl_mae_event_cat', 'titleField'=>'title', 'searchField'=>'title'),
    'sql'                     => "blob NULL"
);`
