### ISSUE TITLE
Kompatibilität mit Contao 5.3

### ISSUE THREAD

**Issue by jankout** [pdir/mae_event_categories#22]
Hallo, 

ich möchte fragen, ob es bald eine neue Version für Contao 5.3 geben wird? Falls ja, sollen wir vielleicht auch eine Spendenaktion starten? Ich wäre schon dabei.

**Comment by Jadascripts** [comment]
Gibt es hier schon Update diesbezüglich? @jankout, hast du hier etwas gehört?

**Comment by jankout** [comment]
Ich wäre schon dabei. @Jadascripts sollen wir uns die Kosten teilen? Was denkst du?

**Comment by MDevster** [comment]
Wir könnten die Erweiterung nächste Woche zu Verfügung stellen.

**Comment by Jadascripts** [comment]
Alles klar, das klingt super :)

Ich bin dabei, @jankout und ich werden uns in dem Fall die Kosten teilen. Wie dürfen wir dir das Geld schicken?

**Comment by jankout** [comment]
Hallo @Jadascripts, wenn du magst, können wir über eine DM kommunizieren.

**Comment by Jadascripts** [comment]
@jankout Ja klar, ich habe dir via Slack geschrieben :)

**Comment by Jadascripts** [comment]
Hallo @MDevster, Jan und ich werden dir nun definitiv die Entwicklung des Bundles mit den 300 Euro zahlen.
Welche Zahlungsart bevorzugst du?

**Comment by jankout** [comment]
@Jadascripts siehe https://github.com/pdir/mae_event_categories/issues/22#issuecomment-2126682579 Da steht auch der Link https://contao-themes.net/sponsoring.html

**Comment by jankout** [comment]
Hallo Mathias, @MDevster ich habe es gerade bezahlt, d.h. im Namen meines Kunden bestellt.

**Comment by Jadascripts** [comment]
Alles klar, danke für die Erklärung. Ich habe es nun ebenfalls gezahlt. 👍 
Wann können wir damit rechnen, dass das Bundle genutzt werden kann?

**Comment by Jadascripts** [comment]
Hallo @MDevster, gibt es hier bereits Neuigkeiten, bis wann das Bundle verfügbar ist? :)

**Comment by MDevster** [comment]
@Jadascripts Sollte bis Freitag der Fall sein

**Comment by Jadascripts** [comment]
Hallo @MDevster, der letzte Freitag liegt ja schon in der Vergangenheit. Bis wann kann das Bundle definitiv bereit sein?

**Comment by MDevster** [comment]
Der Branch ist schon verfügbar seit letzter Woche! Leider haben die Kollegen es noch nicht geschafft ihn zu testen https://github.com/pdir/mae_event_categories/tree/refactor und daher ist noch keine offizielle Version veröffentlicht.

**Comment by Jadascripts** [comment]
Ah cool, danke dir :)
Und bis wann können wir damit rechnen, dass die offizielle Version veröffentlicht wird?

**Comment by Jadascripts** [comment]
Hallo @MDevster
Ich benötige einen verbindlichen Termin für die Fertigstellung des Plugins, da wir dieses für ein Kundenprojekt benötigen und der Kunde bereits darauf wartet. Kannst du uns bitte sagen, wann die finale Version verfügbar sein wird?

**Comment by MDevster** [comment]
Version 1.6.0 has been released.

**Comment by Jadascripts** [comment]
Hallo, vielen Dank fürs Veröffentlichen der Version. Beim Installieren bin ich allerdings schon auf ein Problem gestossen, ich habe dazu ein Issue gemacht: https://github.com/pdir/mae_event_categories/issues/24
Bis wann kannst du dies lösen?
