### ISSUE TITLE
Event Kategorien können nicht installiert werden

### ISSUE THREAD

**Issue by Jadascripts** [pdir/mae_event_categories#24]
Beim Ausführen vom Befehl «composer require pdir/mae_event_categories» wird ein Fehler vom File MaeEventCatModel.php angezeigt:

Compile Error: Type of Pdir\MaeEventCategoriesBundle\Model\MaeEventCatModel::$strTable must not be defined (as in class Contao\Model)

<img width="1780" alt="Bildschirm­foto 2024-06-24 um 07 19 37" src="https://github.com/pdir/mae_event_categories/assets/88333387/f6ad0181-7ebc-4eb1-9775-bcd4abf25d19">

PHP: 8.3
Contao: 5.3.9

**Comment by MDevster** [comment]
@Jadascripts Kannst du bitte dev-master testen? 
![grafik](https://github.com/pdir/mae_event_categories/assets/10244240/d7823a75-767d-4a3e-acaa-f6713d3ee677)

**Comment by Jadascripts** [comment]
Ja jetzt kann es installiert werden. Allerdings sind mir nun nochmals 2 Sachen aufgefallen:

- im File GetAllEventsListener.php ist eine Klasse falsch geschrieben, was einen Fehler schmeisst (Contoa)
- Die Event Kategorien werden im Backend von tl_calendar_events nicht hinzugefügt (auch nach aktualisierter DB und Leeren des Caches)

**Comment by MDevster** [comment]
Danke fürs testen. Bitte aktualisieren, jetzt sollte es passen!

**Comment by Jadascripts** [comment]
Ja, jetzt sieht es gut aus. Danke dir! :)

**Comment by MDevster** [comment]
Ich habe die fehlerhafte Version entfernt und neu veröffentlicht, kann sein das du zum installieren den Composer Cache leeren musst.
