### ISSUE TITLE
Error: Could not find template "mod_mae_event_filter"

### ISSUE THREAD

**Issue by netgroupgmbh** [pdir/mae_event_categories#27]
Hi,
I don't know if I've done something wrong here, since I've never had this error before with contao 4. 
But with Contao 5.3.11 and PHP 8.2.21 and the version 1.6.0 of the bundle, I get an error: 
`request.CRITICAL: Uncaught PHP Exception Exception: "Could not find template "mod_mae_event_filter"" at TemplateLoader.php line 156`
The template is there under vendor/pdir/mae_event_categories/templates/modules but it seems the system doesn't recognize it. When I add it to the contao root "templates" folder, everything works fine.

Could you please have a look at it? 
Cheers!
Adelaide

**Comment by pleenwise** [comment]
Hey, can confirm with:
Contao 4.13.45
PHP 8.1.29
Module 1.6.0

Just went back to 1.5.2 and everything fine here, so @netgroupgmbh i guess we didn't do anything wrong except for updating ;P

Philipp
